source "https://github.com/cocoaPods/Specs.git"
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '12.0'

workspace 'UBiXMediationToolDemo.xcworkspace'

use_frameworks!
inhibit_all_warnings!

use_projects = true

install! 'cocoapods',
        :generate_multiple_pod_projects => use_projects

target 'UBiXMediationToolDemo' do
#  gm_release_target!
#  pod 'UBiMAXAdSDK', :path=>'./UBiMAXSDK/', :subspecs => ['Core']

   pod 'UBiddingAdSDK', '4.0.1'
  pod 'UBiddingUBiXAdapter', '2.11.0.1'
  pod 'UBiddingBaiduAdapter', '10.051.0'
  #pod 'UBiddingCSJAdapter', '7.6.1.7.0'
  pod 'UBiddingFancyAdapter', '2.3.10.2'
  pod 'UBiddingGdtAdapter', '4.15.90.3'
  pod 'UBiddingGromoreAdapter', '7.6.1.7.0'
  pod 'UBiddingIQiYiAdapter', '2.5.002.1'
  pod 'UBiddingJTAdapter', '4.2.3.1.1'
#  pod 'UBiddingKSAdapter', '5.5.10.1.0'
  pod 'UBiddingMeiShuAdapter', '3.0.9.1.2'
  pod 'UBiddingQuMengAdapter', '1.6.0.5.0'
  pod 'UBiddingTopOnAdapter', '6.5.42.2'
  pod 'UBiddingWangMaiAdapter', '7.8.4.32.2'
  pod 'UBiddingJTAdapter','4.2.3.1.1'
  pod 'UBiddingMeiYueAdapter', '5.9.06.0'
  pod 'EdimobIOSAdsSDK', '5.9.06', :subspecs => ['Core', 'CocoaHTTPServer', 'SDWebImage', 'Masonry', 'KSCrash', 'WechatOpenSDK']
  pod 'UBiddingYoushiAdapter', '3.1.0.9.0'
   # 亿帆SDK
   pod 'YFAdsSDK/YFAdsSDK','6.1.4.0'
   # 亿帆适配器
   pod 'UBiMAXYiFanAdapter','6.1.4.0'
   
   
   pod 'Bugly'
   pod 'Masonry'
   pod 'MJRefresh'
   pod 'Protobuf', '3.27.2'
   pod 'YYModel'
   pod 'SDWebImage'

   target 'UBiXMediationToolDemoTests' do
     inherit! :search_paths
   end
end



#target 'UbiXMediation' do
#  pod 'UBiXDaq'
#end

post_install do |installer|
  
  # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
  installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
  end

  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
#    puts "#{target.name}"
  end
end
